function [BW,maskedImage] = MATLAB_image_segmentation_tlbx(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 15-Jun-2021
%----------------------------------------------------

%NOTE: input grayscaled images
%BW contours exceptionally well

% Threshold image - manual threshold
BW = X > 13;

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Clear borders
BW = imclearborder(BW);

% Open mask with octagon
radius = 3;
se = strel('octagon', radius);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

